// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gumfcailbuvfdvbxuizv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bWZjYWlsYnV2ZmR2Ynh1aXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mzc1NTEsImV4cCI6MjA3NDMxMzU1MX0.tA8PYaBRJRfgijvlleUZGAxx1jYz7X-gYL25_a9gTw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});